const DEFAULT_VALUE_IN_SECONDS = 15;

const VALUE_FROM_ENV = Number(
  process.env.NEXT_PUBLIC_REQUEST_TIMEOUT_IN_SECONDS
);

export const REQUEST_TIMEOUT_VALUE = VALUE_FROM_ENV || DEFAULT_VALUE_IN_SECONDS;
